### ISSUE TITLE
Error on session.commit() after session.delete()

### ISSUE THREAD

**Issue by HeyHugo** [operator/sqlalchemy_bulk_lazy_loader#2]
Hi,

I've been troubleshooting an error in sqlalchemy and have found that this package probably was the cause. 

[Here is sqlalchemy mail list thread](https://groups.google.com/d/msg/sqlalchemy/kz47tCpbf-A/5liXDgM2AQAJ) discussing the problem (and full stack trace)

The problem seems to arise when having a relation with `lazy` option set to `joined` from a model that you try to delete.

```python
BulkLazyLoader.register_loader()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)

class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref=db.backref('orders'), lazy='joined')

# Setup db yada yada
# ...

user = User.query.first()
db.session.delete(user)
db.session.commit()  # End of stack trace: ImportError: importlater.resolve_all() hasn't been called (this is sqlalchemy.orm strategy_options)

```

**Comment by chanind** [comment]
Mike's suggestion on the thread you linked looks correct. I'll see if I can reproduce this and then make a release using `from sqlalchemy.orm import 
strategy_options` like Mike suggests. Sorry about that!

**Comment by chanind** [comment]
If you update to v0.9.8 this should now be fixed. Sorry about that, and thanks for helping to get to the bottom of this!

**Comment by HeyHugo** [comment]
Great thanks!
